name: Support-Ticket
version: ${project.version}
main: net.ghostrealms.ticket.SupportTicket
website: ghostrealms.net
commands:
  ticket:
    description: Command for handling tickets
    aliases: [modreq, select, comment, done, pending, priority]